### PR TITLE
Add type definitions for Mori

### PR DESCRIPTION
**Pull request by hallettj**
Glad to see that this repository exists!

### CODE REVIEW

**Comment by jeffmo** [comment]
Thanks! Would you mind adding a `.flowconfig` and a `test.js` file that at least just imports mori (extra credit for additional tests like what's over in [underscore](https://github.com/splodingsocks/FlowTyped/blob/master/underscore/test.js))

**Comment by hallettj** [comment]
I made the changes that you requested, and pushed some fixes to the type definitions.

**Comment by hallettj** [comment]
Ah, now the tests are failing. This is because I tested the mori definitions with Flow v0.22.0, but FlowTyped is on v0.17.0. (And I neglected to run the top-level test-suite before pushing :( ).

**Comment by hallettj** [comment]
It looks like the types for underscore work with flow v0.22.0. I included a flow upgrade in this pull request.

**Comment by splodingsocks** [comment]
I really like this PR, @hallettj. Good job with the tests, and thanks for your contribution!

**Pull request merged**
